### ISSUE TITLE
Throws Error When Checksum is 0

### ISSUE THREAD

**Issue by J0hannB** [ckgt/NemaTode#3]
First off, thank you for this great tool, it works really well. 

The only problem I have occurs when I use a gps that sends checksums. Sometimes I receive a valid NMEA checksum of 0, and the parser treats that as an invalid checksum and throws an error. An example sentence from my GPS: 
`$GPRMC,173138.000,V,3145.5214,N,09704.5057,W,000.0,000.0,170318,000.0,E,N*00`

I get the error:
`GPS Data Bad Format [$GPRMC] :: Checksum is invalid`

**Comment by ckgt** [comment]
Fixed and added to nmea_log.txt for test. Thanks.
